# Generated by Django 3.2.10 on 2022-02-15 16:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='groupName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.UUIDField(default=uuid.uuid1, editable=False, unique=True)),
                ('used', models.BooleanField(default=True)),
            ],
        ),
    ]
