# Generated by Django 3.2.10 on 2022-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
