# Generated by Django 3.2.10 on 2022-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_groupname_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='groupname',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
