# Generated by Django 3.2.10 on 2022-02-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='groupname',
            field=models.CharField(default=8626929982, editable=False, max_length=200, unique=True),
        ),
    ]
