# Generated by Django 3.2.10 on 2022-02-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_groupname_groupname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupname',
            name='groupname',
            field=models.CharField(default='haeidiabcdakhedfeed', max_length=200),
        ),
    ]
