# Generated by Django 3.2.10 on 2022-02-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_groupname_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupname',
            name='username1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groupname',
            name='username2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='groupname',
            name='groupname',
            field=models.CharField(max_length=200),
        ),
    ]
