# Generated by Django 3.2.12 on 2022-02-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_privatechat_privateroomusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroomusers',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
    ]
