# Generated by Django 3.2.12 on 2022-02-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_privateroomusers_is_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privateroomusers',
            name='ownergroup',
        ),
        migrations.DeleteModel(
            name='privateChat',
        ),
        migrations.DeleteModel(
            name='privateRoomUsers',
        ),
    ]
