# Generated by Django 3.2.12 on 2022-02-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_privatechat_privateroomusers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='privateRoomUsers',
        ),
    ]
