# Generated by Django 3.2.12 on 2022-02-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_delete_privateroomusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechat',
            name='noOfUsers',
            field=models.IntegerField(default=1),
        ),
    ]
